### ISSUE TITLE
Light House Scan is not working.

### ISSUE THREAD

**Issue by ravindrai** [gsoft-inc/azure-pipelines-lighthouse#43]
**Describe the bug**
We're trying to run the scan using azure devops yaml pipeline with the following code, but it is giving error . 

Could you please kindly help here.

Also could you please kindly help how to  download the GLH scan reports using azure devops download artifacts.

**Screenshots**
![image](https://user-images.githubusercontent.com/107991579/220304820-867f4d17-915c-4d4a-8788-fa07fdf4dd72.png)

**Environment (please complete the following information):**
azure devops microsoft hosted agent with windows-latest image

Yaml code used:

GLH SCAN:
  - task: Lighthouse@1
    inputs:
      url: 'https://$(json.stagingDomainName)'
      args: '--extra-headers="{\"Authorization\":\"Basic$(MySecretPassword)\"}" --quiet'
      assertions: 'no-vulnerable-libraries=1'

Reports Download Task:
  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)\lighthouse-reports'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

**Comment by asimmon** [comment]
Hi @ravindrai, I looked into [Google Lighthouse](https://github.com/GoogleChrome/lighthouse) changelog and starting Lighthouse 10.x, **they removed the audit** `no-vulnerable-libraries` in this [pull request](https://github.com/GoogleChrome/lighthouse/pull/14194).

If you really need this audit, you need to pre-install the 9.x version of Lighthouse on the build agent. I'll also need to update this project's README because I use this audit in examples and screenshots.

Also, if you need is really to detect vulnerabilities, I would recommend to use a dedicated/real code scanning tool such as [Semgrep](https://semgrep.dev/docs/). Here's a Azure DevOps pipeline that runs Semgrep on pull requests and a weekly schedule: https://gist.github.com/asimmon/2521ac55b612b57f528849f0a5efc48e

**Comment by ravindrai** [comment]
Thanks asimmon for the quick help.

As a work around can i remove the  assertions: 'no-vulnerable-libraries=1' paramter and run the job would it work like this?

Also please suggest how do i copy the GLH scan reports and download it later in the future.

Kindly please suggest.

**Comment by ravindrai** [comment]
After removing that parameter assertions: 'no-vulnerable-libraries=1' i got the below error kindly please help me here

Error:

![image](https://user-images.githubusercontent.com/107991579/220528187-74f94c04-cbc1-4e84-a34c-bd822e74ee52.png)

**Comment by asimmon** [comment]
I managed to reproduce your issue.

But before, I'd like to know if you tried to copy the sample configuration that was on this project's README screenshot? I'm talking about the `no-vulnerable-libraries = 1` and `--extra-headers="{\"Authorization\":\"Basic $(MySecretPassword)\"}" --quiet`.

Because if you did, please understand that was just example values. We've already talked about `no-vulnerable-libraries = 1` (which does no longer exists in Lighthouse). The `--extra-headers=[...]` is also just an example of how one could add extra HTTP headers to do basic authentication. If you don't need that, remove the CLI argument. Please also note that in this example, `MySecretPassword` in a secret that must be defined in Azure DevOps.

So the reason why you have an `Unexpected token A in JSON at position 1` error is because you made a typo.

* You wrote this argument: `--extra-headers={Authorization:Basic$(MySecretPassword)}`
* This is the correct argument: `--extra-headers="{\"Authorization\":\"Basic $(MySecretPassword)\"}" --quiet`
  * Notice we escape some strings here
  * Notice the space between `Basic` and the `$(MySecretPassword)` secret variable

I would recommend you learn more about [Lighthouse on its documentation page](https://github.com/GoogleChrome/lighthouse#cli-options). It's also easy to reproduce the behavior of this Azure Pipeline task locally. All you have to do is:
* Install [Node.js](https://nodejs.org/en/download/) (preferably LTS)
* Execute Lighthouse locally with any CLI option you want to test: 

```ps1
npx lighthouse "https://yourwebsite.com" --quiet --output=html --output=json --output-path="/path/to/report-filename" --chrome-flags="--headless"
```

**Comment by asimmon** [comment]
Also if you look at the logs, the JSON and HTML reports are saved in `$(Agent.TempDirectory)/__lighthouse/` so you can backup the HTML and JSON reports files.
![image](https://user-images.githubusercontent.com/14242083/221476531-326f9daf-f05b-4682-8dd9-c3055f787350.png)

**Comment by ravindrai** [comment]
asimmon Many thanks for the help and it is working as expected. Really thankful to you once again.

All these days we're running light house job in windows based agent at azure devops, is it really necessary to run so?

Also could you please kindly share more details how to run GLH on linux based agent with the command you've given in the above :

npx lighthouse "https://yourwebsite.com" --quiet --output=html --output=json --output-path="/path/to/report-filename" --chrome-flags="--headless"

**Comment by asimmon** [comment]
@ravindrai glad to help but I think I will close the issue, because it's not directly related to this task. At this point it's more like how to configure Azure DevOps and how to consume Google Lighthouse. I will still answer to your questions:

You don't need a Windows based agent in Azure DevOps, it's actually slower than Ubuntu agents. Read this Azure DevOps documentation to understand how to change your build agent, whether you use YAML or Classic pipelines:
https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/pools-queues?view=azure-devops&tabs=classic%2Cbrowser#designate-a-pool-in-your-pipeline

The Lighthouse CLI arguments don't change if it's Windows or Linux. Once again I recommend you to get familiar with the CLI [by reading its documentation](https://github.com/GoogleChrome/lighthouse#cli-options). Once you tried it on your computer and you find the right arguments you need (or maybe you don't need any other), copy paste these arguments to this task.
